version = 1

test_patterns = [
  "app/**",
  "resources/js/pages/**",
  "routes/**"
]

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["nodejs"]